### ISSUE TITLE
Games not detected if their installation folder isn't their exact title

### ISSUE THREAD

**Issue by CharoSW** [sharkwouter/minigalaxy#15]
The GOG installers that you download off their website omit certain characters when creating the installation folder.  The characters I have found that have been omitted are : and -.  There are quite possibly more characters but I don't have any examples in my library.  As these characters don't exist in the folder but do in the game title they aren't detected by Minigalaxy on startup.

**Comment by sharkwouter** [comment]
Thanks for reporting! I'll investigate how the GOG installers pick a name.

**Comment by sharkwouter** [comment]
I've found a way to fix this issue and implemented it. Each GOG game directory contains a file called gameinfo which contains the name of the game. Minigalaxy will now search for these files in the installation path and set games it finds to installed.

**Comment by Archehandoro** [comment]
I have 4 games installed from GOG, previously to trying Minigalaxy. With the default folder name, Minigalaxy finds and recognises a game is installed (for example, Supraland). However, if I have changed the folder name (e.g, from tr berbrook to truberbrook or from Divinity Sin to Divinity_Sin) and these aren't being recognized by Minigalaxy.

Would be possible to apply some regex to a folder name to improve the feature?

Thanks :D

**Comment by sharkwouter** [comment]
With the method I implemented yesterday the folder name shouldn't matter at all anymore. If you'd like to help test it you can use the ``Without VENV`` instructions in [here](https://github.com/sharkwouter/minigalaxy/blob/master/README.md#installation). That way we can make sure it works well in the next release :)

**Comment by Archehandoro** [comment]
Unfortunately, that way does not work for me either.

This is what I've done:
Download/Installed "Without Venv" as per your instructions.
Installed with GOG installer, changing spaces with _.
Game still not recognized.

:(

**Comment by sharkwouter** [comment]
Thanks for testing, I'll check to see if I have the same issue

**Comment by sharkwouter** [comment]
@Archehandoro which games did you have issues with? Do they have a file called ``gameinfo`` in their directories?

**Comment by sharkwouter** [comment]
Okay, I think I've encountered the issue now while working on the offline mode. It seems to affect at least the following games for me:
- Beneath a Steel Sky (Beneath A Steel Sky in gameinfo file)
- LOOM™ (Loom™ in gaminfo file)
- X Rebirth (X: Rebirth in gameinfo file)

The title in the gameinfo file is not the same as the title in the API for these games. If you go start in offline mode they are detected. If you go in online mode again after that, the game will show up twice with different titles.

I'll need to do some filtering to make sure:
- Capital letters don't matter
- Special characters don't matter

**Comment by sharkwouter** [comment]
I've added the filtering I mentioned in the previous reply in commit 10e7c98fea693bc409a946d7de355486464c1b2a. It should now work better. Could someone test this again?

There is a limitation to this. It will not show games which you do not own, unless you're in offline mode.

**Comment by sharkwouter** [comment]
Has been fixed with a72e157f9dcceb2d41a661d7a762e84a93e719b4

**Comment by Archehandoro** [comment]
> @Archehandoro which games did you have issues with? Do they have a file called `gameinfo` in their directories?

Sorry for late reply. I tried with Blade Runner, Divinity Original Sin, Knights & Bikes, Trüberbrook and Pillars of Eternity II. Yes, they do have the gameinfo file.

**Comment by Archehandoro** [comment]
Thanks for fixing it :D
